export const MATS = {
  vacuum: {
    kappa: 1.0,
    slabColor: 0x173047,
    slabEmissive: 0x0a1a2b,
    dipColor: 0x88ccff,
    bindE: 9999,
    label: 'Vacuum',
    paramDisplay: 'k = 1.0',
    alignSpeed: 0.9,
    log: 'Pure vacuum. No material. The baseline against which all dielectrics are measured.',
  },
  glass: {
    kappa: 4.7,
    slabColor: 0x3d85b8,
    slabEmissive: 0x153a52,
    dipColor: 0xaaddff,
    bindE: 3.5,
    label: 'Borosilicate',
    paramDisplay: 'k = 4.7',
    alignSpeed: 1.3,
    log: 'Borosilicate glass - <span class="lk">k = 4.7</span>. Dipoles barely flex. A reluctant rememberer.',
  },
  water: {
    kappa: 80.0,
    slabColor: 0x2c58c2,
    slabEmissive: 0x102b66,
    dipColor: 0x44aaff,
    bindE: 0.7,
    label: 'Water H2O',
    paramDisplay: 'k = 80',
    alignSpeed: 1.8,
    chaos: true,
    log: 'Water - <span class="lk">k = 80</span>. Chaos resolving into order. An 80x surge in capacitance.',
  },
  barium: {
    kappa: 1200.0,
    slabColor: 0xb95d22,
    slabEmissive: 0x5a2a0d,
    dipColor: 0xffaa44,
    bindE: 0.1,
    label: 'BaTiO3',
    paramDisplay: 'k = 1200',
    alignSpeed: 3.4,
    climax: true,
    log: 'Barium titanate - <span class="la">k = 1200</span>. Cascading crystalline alignment. The Amplifier.',
  },
};
